export const messages={
  SeriesInactive:"This maturity is not accepting new purchases. Purchases close one hour before maturity. Existing tickets can still exit.",
  IndexCircuitBreaker:"The vault price moved beyond its safety limit. New purchases are paused.",
  SeriesCapExceeded:"This series has reached its 500 USDC entry cap. Choose another maturity.",
  VaultDepositLimit:"The vault is not accepting this deposit amount right now.",
  VaultRedeemLimit:"The vault has limited withdrawal liquidity. Choose vault shares instead.",
  VaultIlliquid:"There is not enough USDC available in the vault. Choose vault shares instead.",
  PurchaseCapExceeded:"A ticket cannot cost more than its USDC face value.",
  PriceAboveFace:"The pool price is above face value. Wait for a better quote.",
  IncompleteFill:"There is not enough pool liquidity for this amount. Try a smaller amount.",
  PoolNotSet:"This maturity does not have a liquidity pool yet.",
  SlippageExceeded:"The price moved beyond your limit. Refresh the quote.",
  DeadlineExpired:"Your quote expired. Request a fresh quote.",
  SeriesExpired:"This maturity has expired. Use Cash out in Positions.",
  ExpiredSeries:"An expired maturity cannot be registered for new purchases.",
  SeriesNotExpired:"This ticket has not matured. You can sell it early if the pool has liquidity.",
  PaymentCapExceeded:"This payment exceeds the daily or rolling 30-day payee limit.",
  PayeeBlacklisted:"USDC has blocked this payee address. Other approved payees can still be paid.",
  TreasuryBlacklisted:"USDC has blocked this treasury address. Contact the issuer before trying again.",
  PaymentFailed:"USDC could not complete this payment. Your spending limits were not charged.",
  PayeeHistoryFull:"This payee has reached the limit of 128 active payment timestamps. Wait for older payments to expire.",
  AgentPaused:"The owner has paused this agent. Owner withdrawals remain available.",
  Unauthorized:"This wallet is not authorized for this treasury action.",
  OnlyOwner:"Only the owner wallet can make this change.",OnlyYieldToken:"Only the paired yield contract can create or burn principal tickets.",
  UnsupportedToken:"Tijori accepts only USDC and registered PT/YT tokens. Registered vault shares use a separate recovery action.",
  InvalidAmount:"Enter a positive amount with up to six decimal places.",InvalidReceiver:"Choose a valid recipient wallet.",
  InvalidPayee:"Choose a valid approved payee address.",InvalidLadder:"Select valid, unique maturities and a nonzero budget.",
  BudgetExceeded:"The purchases exceed your total spending budget.",UnexpectedTransferAmount:"The token transfer credited an unexpected amount. No purchase was completed.",
  UnsupportedChain:"Switch your wallet to the Arc network this app uses.",InvalidConfiguration:"The deployed contracts do not match the configured system.",
  InvalidVault:"This address is not a supported USDC vault.",InvalidAsset:"The vault or registry has the wrong USDC asset.",
  InvalidExpiry:"Choose a maturity in the future.",UnsupportedShareDecimals:"This vault's share decimals are not supported.",
  ZeroIndex:"The vault reported an invalid share price. Stop and check the vault.",
  InvalidOwner:"Choose a valid owner wallet.",InvalidSeries:"This contract is not a valid registered series.",
  UnknownSeries:"This maturity is not registered.",SeriesAlreadyRegistered:"This series is already registered.",
  VaultExpiryAlreadyRegistered:"A series for this vault and date already exists.",PoolAlreadySet:"This series already has an immutable pool key.",
  InvalidPoolKey:"The pool currencies or settings do not match this series.",UnauthorizedCallback:"The pool callback could not be verified. The transaction was stopped.",
  AlreadyExists:"You already have a Tijori. Open your existing treasury.",AlreadyInitialized:"This Tijori is already initialized.",
  FailedDeployment:"The treasury clone could not be created. Check the factory deployment before retrying.",
  InsufficientBalance:"There is not enough native gas USDC for this deployment action.",
  InvalidQuote:"The pool did not return a valid quote. Try another maturity.",QuoteResult:"Refresh the quote before submitting a purchase.",
  ERC20InsufficientBalance:"Your token balance is too low for this action.",ERC20InsufficientAllowance:"Approve the required token amount before continuing.",
  ERC20InvalidSender:"The token sender address is invalid.",ERC20InvalidReceiver:"The token receiver address is invalid.",
  ERC20InvalidApprover:"The approval sender address is invalid.",ERC20InvalidSpender:"The approval destination is invalid.",
  ERC4626ExceededMaxDeposit:"The vault deposit cap is full. Try another maturity.",ERC4626ExceededMaxMint:"The vault cannot mint this many shares right now.",
  ERC4626ExceededMaxWithdraw:"The vault cannot withdraw this amount. Choose shares instead.",ERC4626ExceededMaxRedeem:"The vault cannot redeem this many shares. Choose shares instead.",
  SafeERC20FailedOperation:"The token transfer failed. Check balance and token restrictions.",ReentrancyGuardReentrantCall:"This action attempted to run twice inside one transaction and was stopped.",
  TESTNET_DEPLOYMENT_MISSING:"No deployment is configured yet. Rates will appear after deployment and seeding.",
  SERVICE_UNAVAILABLE:"The quote service is unavailable. Wait and refresh before sending funds.",STALE_RPC_BLOCK:"The RPC is behind the chain. Wait for a fresh quote.",
  SERIES_MATURED:"This maturity has expired. Use Cash out in Positions.",SERIES_HAS_NO_POOL:"This maturity has no pool liquidity yet.",
  NO_DISCOUNTED_QUOTE:"There is no discounted quote available for this amount.",INVALID_QUOTE_AMOUNT:"Enter a positive USDC face value with up to six decimals.",
  QUOTER_EXECUTION_MISMATCH:"The quoter and execution price do not match. Purchases have been stopped.",QUOTER_MANAGER_MISMATCH:"The configured quoter uses the wrong pool manager.",
  WRONG_RPC_CHAIN:"The quote service is connected to the wrong network.",QUOTE_CHANGED:"The price changed since review. Review a fresh quote before locking.",
  DEPLOYMENT_MISMATCH:"The configured addresses do not match the deployed system. Stop and check the deployment manifest.",
  WRONG_WALLET_NETWORK:"Switch your wallet to the Arc network this app uses to continue.",WALLET_REQUIRED:"Open this app in a wallet browser or install an Ethereum wallet.",
  BATCH_PENDING:"An earlier purchase is still unconfirmed by your wallet. Wallet actions are paused until it confirms or its deadline passes, within about two minutes. Then try again.",
  BATCH_EXPIRED:"Your wallet never confirmed the purchase and its deadline has passed. Refresh positions to see whether it went through.",
  BATCH_FAILED:"The wallet batch failed. Review its status before retrying.",BATCH_NOT_ATOMIC:"The wallet did not confirm atomic execution. Review the batch before proceeding.",
  INVALID_SEED_PRICE:"Enter an opening PT price above 0 and at most 1 USDC.",INSUFFICIENT_SEED_FUNDS:"This wallet needs the PT budget plus the USDC budget in USDC before seeding.",
  ACCOUNT_CHANGED:"Your wallet account changed. Reconnect and review the transaction.",ACTION_REJECTED:"You cancelled the wallet request.",
};
export function humanError(error,interfaces=[]) {
  if(error.code===4001 || error.code==="ACTION_REJECTED") return messages.ACTION_REJECTED;
  const data=error.data??error.info?.error?.data;
  for(const iface of interfaces) try{const parsed=iface.parseError(typeof data==="string"?data:data?.data);if(messages[parsed?.name]) return messages[parsed.name];}catch{}
  return messages[error.code]??messages[error.message]??"This action could not be completed. Check your network, balance and limits, then refresh.";
}
